###
POST http://localhost:3000/api/product HTTP/1.1
Content-Type: application/json

{ 
  "nome": "Ração Fórmula Natural Life",
  "marca" : "Fórmula Natural",
  "preço": 275.9,
  "tipo" : "Adultos"
}
###
GET http://localhost:3000/api/product HTTP/1.1

###
GET http://localhost:3000/api/product/6137e2bb2e329eb206b0073e HTTP/1.1

###

DELETE http://localhost:3000/api/product/63211944b683f8e18043120e HTTP/1.1


###
PUT http://localhost:3000/api/product/6137e2412e329eb206b0073c HTTP/1.1

Content-Type: application/json

{
  "name": "sab